# Generated by Django 4.0.6 on 2022-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0002_rename_token_json_customuser_credentials_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
